### ISSUE TITLE
Some basic extensions doesn't work

### ISSUE THREAD

**Issue by darekbienkowski** [benhutchins/docker-mediawiki#23]
I need to use SyntaxHighlight and WikiEditor. Even are basic - they not works. I tried to change in docker extensions folder with new version of plugins, and to install with LocalSettings.php inside basic docker folder var/www/html without map VOLUMES, but still nothing .
I tested on version 1.30 and 1.27 - a same results.
Any idea why some extension not works ?

**Comment by benhutchins** [comment]
`SyntaxHighlight` requires `python`, which is not included as part of the images.

You may want to use the https://github.com/wikimedia/mediawiki-docker supplied version which does include `python`, so might have an easier time using that.

The WikiEditor should work as-is, but if you're trying to use the SyntaxHighlight then it might not work since it needs python.

**Comment by darekbienkowski** [comment]
Thanks for reply. 
Suggestion https://github.com/wikimedia/mediawiki-docker is very helpful, but I need to use a psql... I will try to figure it out how to do it.
